import Anthropic from "@anthropic-ai/sdk";

interface Msg {
  role: "user" | "assistant";
  content: string;
}

// A small, fast model is the right tool here: this is a cheap pre-retrieval
// step that runs before every follow-up, so latency and cost matter more than
// raw capability. The main answer is still generated by the primary model.
const REWRITE_MODEL = "claude-haiku-4-5";

const REWRITE_SYSTEM = `You rewrite a user's latest message into a single standalone \
search query for retrieving information about Riley Greiff's projects and experience.

Using the conversation so far, resolve references in the latest message — pronouns like \
"it" / "that", and phrases like "the second one" or "that project" — into an explicit, \
self-contained query.

Rules:
- Output ONLY the rewritten query text. No quotes, no preamble, no explanation.
- If the latest message is already self-contained, return it essentially unchanged.
- Keep it concise and focused on retrievable content.`;

/**
 * Turn a possibly-context-dependent follow-up into a standalone query for
 * retrieval. Used only to drive the vector search — the original message still
 * drives the generated answer. Fails open: on any error, returns the raw
 * message so chat keeps working.
 */
export async function rewriteQuery(messages: Msg[]): Promise<string> {
  const last = messages[messages.length - 1].content;

  // First turn (or no prior context) — nothing to resolve, skip the extra call.
  if (messages.length <= 1) return last;

  try {
    const client = new Anthropic();
    const transcript = messages
      .map((m) => `${m.role === "user" ? "User" : "Assistant"}: ${m.content}`)
      .join("\n");

    const res = await client.messages.create({
      model: REWRITE_MODEL,
      max_tokens: 128,
      system: REWRITE_SYSTEM,
      messages: [
        {
          role: "user",
          content: `Conversation:\n${transcript}\n\nRewrite the last User message into a standalone search query.`,
        },
      ],
    });

    const block = res.content.find((b) => b.type === "text");
    const rewritten = block && block.type === "text" ? block.text.trim() : "";
    return rewritten || last;
  } catch (err) {
    console.error("query rewrite failed (falling back to raw message):", err);
    return last;
  }
}
